### PR TITLE
set up Travis

### PR DESCRIPTION
**Pull request by simonzachau**
set up Travis with the .travis.yml file

### CODE REVIEW

**Comment by simonzachau** [comment]
```Failed to clone 'api'```.
How is this error to be solved? See also the question of group2 in the Lobby.

**Comment by simonzachau** [comment]
How do we signal Travis that when the servers are starting up it's a successful build? Otherwise it keeps running forever.

**Review by FelsyWaschbaer — COMMENTED** [review]
Travis does not finish because "docker-compose up" is called which starts the docker containers and blocks the process. You could use "docker-compose build" but we can only push single images to docker hub if we take the way described in #40

**Comment by simonzachau** [comment]
@FelsyWaschbaer thanks, ```docker-compose build``` works! When we continue our setup with Azure we can skip the nlp and push a single image.

**Review by FelsyWaschbaer — APPROVED** [review]

**Comment by sacdallago** [comment]
Oh no please! Don't change ssh for HTTP. For travis, there is an [on-the-fly workaround](http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci/24600210#24600210).

**Comment by simonzachau** [comment]
@sacdallago ok, then I'm going to use this!

**Pull request merged**
